export interface DockItem {
  id: string;
  name: string;
  href: string;
  bgGradient: string;
  color: string;
  iconUrl: string;
}

export const dockItems: DockItem[] = [
  {
    id: "home",
    name: "Home",
    href: "/",
    bgGradient: "bg-gradient-to-br from-slate-500 via-slate-600 to-slate-700",
    color: "text-slate-300",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/1946/1946488.png",
  },
  {
    id: "training",
    name: "Live Training",
    href: "/training",
    bgGradient: "bg-gradient-to-br from-emerald-500 via-cyan-600 to-blue-700",
    color: "text-emerald-400",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/2103/2103832.png",
  },
  {
    id: "demo",
    name: "VoxFormer Demo",
    href: "/demo",
    bgGradient: "bg-gradient-to-br from-cyan-500 via-purple-600 to-pink-700",
    color: "text-cyan-400",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/3845/3845731.png",
  },
  {
    id: "full_presentation",
    name: "Full Pipeline",
    href: "/full_presentation",
    bgGradient: "bg-gradient-to-br from-cyan-500 via-purple-600 to-orange-600",
    color: "text-cyan-400",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/1903/1903496.png",
  },
  {
    id: "full_demo",
    name: "Full Demo",
    href: "/full_demo",
    bgGradient: "bg-gradient-to-br from-cyan-500 via-pink-500 to-orange-500",
    color: "text-cyan-400",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/3135/3135768.png",
  },
  {
    id: "technical",
    name: "VoxFormer STT",
    href: "/technical",
    bgGradient: "bg-gradient-to-br from-cyan-500 via-cyan-600 to-teal-700",
    color: "text-cyan-400",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/4712/4712027.png",
  },
  {
    id: "rag",
    name: "Advanced RAG",
    href: "/rag",
    bgGradient: "bg-gradient-to-br from-emerald-500 via-green-600 to-teal-700",
    color: "text-emerald-400",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/2103/2103658.png",
  },
  {
    id: "rag_demo",
    name: "RAG Demo",
    href: "/rag_demo",
    bgGradient: "bg-gradient-to-br from-emerald-500 via-cyan-600 to-teal-700",
    color: "text-emerald-400",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/4712/4712035.png",
  },
  {
    id: "avatar",
    name: "TTS + LipSync",
    href: "/avatar",
    bgGradient: "bg-gradient-to-br from-rose-500 via-pink-600 to-fuchsia-700",
    color: "text-rose-400",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/4712/4712109.png",
  },
  {
    id: "avatar_demo",
    name: "Avatar Demo",
    href: "/avatar_demo",
    bgGradient: "bg-gradient-to-br from-rose-500 via-purple-600 to-cyan-700",
    color: "text-rose-400",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
  },
  {
    id: "mcp",
    name: "Blender MCP",
    href: "/mcp",
    bgGradient: "bg-gradient-to-br from-orange-500 via-amber-600 to-yellow-700",
    color: "text-orange-400",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/5969/5969136.png",
  },
  {
    id: "docs",
    name: "Documentation",
    href: "/docs",
    bgGradient: "bg-gradient-to-br from-indigo-500 via-violet-600 to-purple-700",
    color: "text-indigo-400",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/2991/2991112.png",
  },
  {
    id: "implementation",
    name: "Task Tracker",
    href: "/implementation",
    bgGradient: "bg-gradient-to-br from-sky-500 via-blue-600 to-indigo-700",
    color: "text-sky-400",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/9746/9746379.png",
  },
  {
    id: "team",
    name: "Team",
    href: "/team",
    bgGradient: "bg-gradient-to-br from-violet-500 via-purple-600 to-fuchsia-700",
    color: "text-violet-400",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/681/681494.png",
  },
  {
    id: "activity",
    name: "Activity",
    href: "/activity",
    bgGradient: "bg-gradient-to-br from-amber-500 via-orange-600 to-red-700",
    color: "text-amber-400",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/3524/3524335.png",
  },
  {
    id: "milestones",
    name: "Milestones",
    href: "/milestones",
    bgGradient: "bg-gradient-to-br from-teal-500 via-cyan-600 to-blue-700",
    color: "text-teal-400",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/4185/4185501.png",
  },
  {
    id: "secrets",
    name: "Secrets Vault",
    href: "/secrets",
    bgGradient: "bg-gradient-to-br from-red-600 via-rose-700 to-pink-800",
    color: "text-red-400",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/3064/3064197.png",
  },
  {
    id: "resources",
    name: "Resources",
    href: "/resources",
    bgGradient: "bg-gradient-to-br from-lime-500 via-green-600 to-emerald-700",
    color: "text-lime-400",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/2991/2991148.png",
  },
  {
    id: "glossary",
    name: "Glossary",
    href: "/glossary",
    bgGradient: "bg-gradient-to-br from-fuchsia-500 via-pink-600 to-rose-700",
    color: "text-fuchsia-400",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/2232/2232688.png",
  },
  {
    id: "decisions",
    name: "Decisions",
    href: "/decisions",
    bgGradient: "bg-gradient-to-br from-slate-500 via-gray-600 to-zinc-700",
    color: "text-slate-400",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/1584/1584892.png",
  },
  {
    id: "changelog",
    name: "Changelog",
    href: "/changelog",
    bgGradient: "bg-gradient-to-br from-cyan-600 via-teal-700 to-emerald-800",
    color: "text-cyan-400",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/1828/1828833.png",
  },
  {
    id: "context",
    name: "LLM Context",
    href: "/context",
    bgGradient: "bg-gradient-to-br from-purple-600 via-violet-700 to-indigo-800",
    color: "text-purple-400",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/8618/8618881.png",
  },
];
